version: "3.8"
services:
  backend:
    build: ./backend
    image: devkojo/weather-backend:local
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: "http://localhost:5000"
    image: devkojo/weather-frontend:local
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
